to-do-list
MariamOsman11/todo-list pull request #1
Opened 2023-06-15 22:47 UTC by MariamOsman11

# What I did

- Set up a new project with webpack that is based on the webpack exercise you have already completed.
- Create an index.html file and write your HTML markup here. Create an empty To Do List placeholder (<div> or <ul> element
- Write a function to iterate over the tasks array and populate an HTML list item element for each task.
- Create a style.css and set rules for the To Do List
- All your source files (index.html, index.js and style.css) must be located in /src directory and your distribution files will be generated by webpack and served by webpack dev server from /dist folder.

2023-06-15 23:53 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @MariamOsman11  :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Descriptive pull request.
✔️ Follow the correct Git flow.
✔️ Professional Readme.
✔️ Application is working fine.

## Required Changes ♻️

***Please kindly check the comments/review below.***

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 23:53 UTC, Tufahel commented on src/index.js
> +];
- [ ] Here I can see you have used `index: 5` for both `object` but it should be different, cause as per the requirements `The tasks should appear in order of the index values for each task.` Kindly fix this issue.

2023-06-15 23:53 UTC, Tufahel commented on README.md
> +
- [ ] Here `[LinkedIn](https://www.linkedin.com/in/marian-isman-a57b75226/)` this link is giving an error and the next two links `GitHub:https://github.com/Kanyorok [LinkedIn](https://github.com/Kanyorok)` are not related to your project. Kindly this issue.

2023-06-15 23:53 UTC, Tufahel commented on src/style.css
> +}
- ***[OPTIONAL]*** 
![image](https://github.com/MariamOsman11/todo-list/assets/60083437/39c4f338-952d-4cc0-85b6-c781e53ad60d)
- [ ] Here I can see you have used three colors that have too much contrast and are not suitable for the eyes. It is very hard for me to read the text. One is `gradient for background` another is `red for tasklist` and the last one is `green for clear button`. I would recommend you to use a `light` color, such as the design given in the project requirement.

2023-06-16 07:57 UTC, abdallahmalima requested changes
Hi @MariamOsman11 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![A little bit more](https://user-images.githubusercontent.com/20554583/208236462-13ccd332-b921-416b-a8a9-b831ebd7c79b.gif)


 ## Highlights
- Setup `webpack`.✔️
- Configure HTML `Webpack`Plugin✔️
- Dynamically  render to the `DOM`✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._✔️

2023-06-16 07:57 UTC, abdallahmalima commented on README.md
> +- GitHub:https://github.com/Kanyorok
-  [ ] 🙏Please ensure that all the links provided here are correct✅ and currently working. Currently, some of them are incorrect❎, and some are broken. This will make it easier for someone to reach out to you as a project developer.

2023-06-16 08:16 UTC, 1GORDON reviewed
##
## Hi @MariamOsman11 ✋

Good job so far!
Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ] Kindly remove the live demo link from your readme file since this project is not yet deployed.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 08:40 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @MariamOsman11 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Webpack used correctly to set up the project ✔️ 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-06-16 08:41 UTC, merged